/**
 * Canonical texture names. The renderer in packages/client looks textures up by
 * these exact strings, so the spelling is part of the contract. `missing` must
 * stay first: it is the fallback tile at atlas index 0.
 */
export const REQUIRED_TEXTURES: readonly string[] = [
  'missing',
  'stone',
  'cobblestone',
  'dirt',
  'grass_top',
  'grass_side',
  'sand',
  'sandstone',
  'gravel',
  'snow',
  'ice',
  'water',
  'lava',
  'bedrock',
  'clay',
  'oak_log',
  'oak_log_top',
  'oak_leaves',
  'birch_log',
  'birch_log_top',
  'birch_leaves',
  'spruce_log',
  'spruce_log_top',
  'spruce_leaves',
  'cactus_side',
  'cactus_top',
  'tall_grass',
  'dead_bush',
  'flower_red',
  'flower_yellow',
  'oak_sapling',
  'coal_ore',
  'iron_ore',
  'gold_ore',
  'diamond_ore',
  'redstone_ore',
  'lapis_ore',
  'planks',
  'glass',
  'crafting_table_top',
  'crafting_table_side',
  'furnace_front',
  'furnace_front_lit',
  'furnace_side',
  'furnace_top',
  'chest_front',
  'chest_side',
  'chest_top',
  'torch',
  'glowstone',
  'door_lower',
  'door_upper',
  'bed_foot',
  'bed_head',
  'redstone_wire',
  'lever',
  'button',
  'pressure_plate',
  'redstone_lamp',
  'redstone_lamp_lit',
  'piston_side',
  'piston_top',
  'piston_head',
  'stone_bricks',
  'bricks',
  'obsidian',
  'snow_layer',
  'iron_block',
  'gold_block',
  'diamond_block',
  'coal_block',
  'wool',
  'ladder',
]

/** Binary alpha (0 or 255) after generation: drawn in the cutout render layer. */
export const CUTOUT_TEXTURES: readonly string[] = [
  'oak_leaves',
  'birch_leaves',
  'spruce_leaves',
  'tall_grass',
  'dead_bush',
  'flower_red',
  'flower_yellow',
  'oak_sapling',
  'torch',
  'ladder',
  'door_lower',
  'door_upper',
  'redstone_wire',
]

/** Partially transparent: these keep their 0 < alpha < 255 pixels. */
export const TRANSLUCENT_TEXTURES: readonly string[] = ['water', 'ice', 'glass', 'lava']
