/**
 * v2 blocks and items, as registries this app can actually use.
 *
 * `packages/gameplay` defines BLOCKS and ITEMS for the v1 ids only. The v2
 * contract ids - netherrack, farmland, the crops, the enchanting table - exist
 * in `@voxelcraft/core-types` and are generated by `@voxelcraft/world`, but no
 * registry entry describes them, so `BLOCKS.tryById(BLOCK_V2.FARMLAND)` is
 * `undefined`: nothing could be named, placed or dropped. Both packages are
 * frozen for this task, so apps/game builds merged registries here instead of
 * editing them.
 *
 * Each definition is spread from the stone definition, so the frozen fields
 * this app has no opinion about (texture keys, fluid, block entity, gravity,
 * redstone) keep their shape, and every field that matters for a v2 block is
 * then set explicitly. Rendering does not read these texture keys: the mesher
 * appearance table of `@voxelcraft/client` already covers the v2 ids.
 */
import {
	BLOCK,
	BLOCK_V2,
	INVENTORY,
	PORTAL,
	RENDER_LAYER,
	SOUND_GROUP,
	TOOL_CLASS,
	TOOL_TIER,
	type BlockDef,
	type BlockId,
	type ItemDef,
	type ItemId,
} from '@voxelcraft/core-types'
import {
	BLOCK_DEFS,
	ITEM_DEFS,
	ITEM_V2_DEFS,
	createBlockRegistry,
	createItemRegistry,
	drop,
	type GameplayBlockRegistry,
	type GameplayItemRegistry,
} from '@voxelcraft/gameplay'

function requireV1(id: BlockId): BlockDef {
	const def = BLOCK_DEFS.find((entry) => entry.id === id)
	if (def === undefined) throw new Error(`the v1 block table is missing block ${id}`)
	return def
}

const STONE_DEF: BlockDef = requireV1(BLOCK.STONE)

type V2Overrides = Partial<Omit<BlockDef, 'id' | 'name' | 'displayName'>>

function v2Block(
	id: BlockId,
	name: string,
	displayName: string,
	overrides: V2Overrides = {},
): BlockDef {
	return {
		...STONE_DEF,
		id,
		name,
		displayName,
		layer: RENDER_LAYER.Opaque,
		solid: true,
		fullCube: true,
		replaceable: false,
		opacity: 15,
		emission: 0,
		skyPassThrough: false,
		hardness: 1,
		toolClass: TOOL_CLASS.None,
		minTier: TOOL_TIER.None,
		soundGroup: SOUND_GROUP.Stone,
		flammable: false,
		drops: [drop(id)],
		itemId: id,
		...overrides,
	}
}

/** A crop: no collider, no light blocking, broken by hand, dropped by harvest. */
const CROP: V2Overrides = {
	layer: RENDER_LAYER.Cutout,
	solid: false,
	fullCube: false,
	opacity: 0,
	skyPassThrough: true,
	hardness: 0,
	soundGroup: SOUND_GROUP.Plant,
	flammable: true,
	drops: [],
}

/** The v2 block definitions, in contract id order. */
export const V2_BLOCK_DEFS: readonly BlockDef[] = [
	v2Block(BLOCK_V2.NETHERRACK, 'netherrack', 'Netherrack', {
		hardness: 0.4,
		toolClass: TOOL_CLASS.Pickaxe,
	}),
	v2Block(BLOCK_V2.NETHER_PORTAL, 'nether_portal', 'Nether Portal', {
		layer: RENDER_LAYER.Translucent,
		solid: false,
		fullCube: false,
		opacity: 0,
		emission: PORTAL.lightLevel,
		skyPassThrough: true,
		hardness: 0,
		drops: [],
	}),
	v2Block(BLOCK_V2.SOUL_SAND, 'soul_sand', 'Soul Sand', {
		hardness: 0.5,
		toolClass: TOOL_CLASS.Shovel,
		soundGroup: SOUND_GROUP.Sand,
	}),
	v2Block(BLOCK_V2.QUARTZ_ORE, 'quartz_ore', 'Nether Quartz Ore', {
		hardness: 3,
		toolClass: TOOL_CLASS.Pickaxe,
		minTier: TOOL_TIER.Wood,
	}),
	v2Block(BLOCK_V2.NETHER_BRICKS, 'nether_bricks', 'Nether Bricks', {
		hardness: 2,
		toolClass: TOOL_CLASS.Pickaxe,
	}),
	v2Block(BLOCK_V2.MAGMA_BLOCK, 'magma_block', 'Magma Block', {
		emission: 3,
		hardness: 0.5,
		toolClass: TOOL_CLASS.Pickaxe,
	}),
	v2Block(BLOCK_V2.FARMLAND, 'farmland', 'Farmland', {
		hardness: 0.6,
		toolClass: TOOL_CLASS.Shovel,
		soundGroup: SOUND_GROUP.Dirt,
		drops: [drop(BLOCK.DIRT)],
	}),
	v2Block(BLOCK_V2.FARMLAND_WET, 'farmland_wet', 'Wet Farmland', {
		hardness: 0.6,
		toolClass: TOOL_CLASS.Shovel,
		soundGroup: SOUND_GROUP.Dirt,
		drops: [drop(BLOCK.DIRT)],
	}),
	v2Block(BLOCK_V2.WHEAT_CROP, 'wheat_crop', 'Wheat', CROP),
	v2Block(BLOCK_V2.CARROT_CROP, 'carrot_crop', 'Carrots', CROP),
	v2Block(BLOCK_V2.POTATO_CROP, 'potato_crop', 'Potatoes', CROP),
	v2Block(BLOCK_V2.ENCHANTING_TABLE, 'enchanting_table', 'Enchanting Table', {
		fullCube: false,
		opacity: 0,
		skyPassThrough: true,
		emission: 7,
		hardness: 5,
		toolClass: TOOL_CLASS.Pickaxe,
		minTier: TOOL_TIER.Wood,
	}),
	v2Block(BLOCK_V2.BOOKSHELF, 'bookshelf', 'Bookshelf', {
		hardness: 1.5,
		toolClass: TOOL_CLASS.Axe,
		soundGroup: SOUND_GROUP.Wood,
		flammable: true,
	}),
	v2Block(BLOCK_V2.GRAVEL_PATH, 'gravel_path', 'Gravel Path', {
		hardness: 0.6,
		toolClass: TOOL_CLASS.Shovel,
		soundGroup: SOUND_GROUP.Dirt,
	}),
	v2Block(BLOCK_V2.COBBLESTONE_WALL, 'cobblestone_wall', 'Cobblestone Wall', {
		fullCube: false,
		opacity: 0,
		skyPassThrough: true,
		hardness: 2,
		toolClass: TOOL_CLASS.Pickaxe,
	}),
	v2Block(BLOCK_V2.HAY_BLOCK, 'hay_block', 'Hay Bale', {
		hardness: 0.5,
		soundGroup: SOUND_GROUP.Plant,
		flammable: true,
	}),
	v2Block(BLOCK_V2.FENCE, 'fence', 'Fence', {
		fullCube: false,
		opacity: 0,
		skyPassThrough: true,
		hardness: 2,
		toolClass: TOOL_CLASS.Axe,
		soundGroup: SOUND_GROUP.Wood,
		flammable: true,
	}),
	v2Block(BLOCK_V2.FENCE_GATE, 'fence_gate', 'Fence Gate', {
		fullCube: false,
		opacity: 0,
		skyPassThrough: true,
		hardness: 2,
		toolClass: TOOL_CLASS.Axe,
		soundGroup: SOUND_GROUP.Wood,
		flammable: true,
	}),
]

/**
 * Blocks that exist in the world but are never an inventory item: the portal
 * plane is lit by flint and steel, farmland comes from a hoe, and a crop comes
 * from planting a seed.
 */
const V2_NON_ITEM_BLOCKS: readonly BlockId[] = [
	BLOCK_V2.NETHER_PORTAL,
	BLOCK_V2.FARMLAND,
	BLOCK_V2.FARMLAND_WET,
	BLOCK_V2.WHEAT_CROP,
	BLOCK_V2.CARROT_CROP,
	BLOCK_V2.POTATO_CROP,
]

function blockItemOf(def: BlockDef): ItemDef {
	return {
		id: def.itemId,
		name: def.name,
		displayName: def.displayName,
		maxStack: INVENTORY.defaultMaxStack,
		texture: def.name,
		toolClass: TOOL_CLASS.None,
		tier: TOOL_TIER.None,
		durability: 0,
		attackDamage: 1,
		food: 0,
		fuelTicks: 0,
		placesBlock: def.id,
	}
}

/** Item definitions for the v2 blocks that can be held and placed. */
export const V2_BLOCK_ITEM_DEFS: readonly ItemDef[] = V2_BLOCK_DEFS.filter(
	(def) => !V2_NON_ITEM_BLOCKS.includes(def.id),
).map(blockItemOf)

/** v1 blocks plus every v2 block. */
export const BLOCKS_V2: GameplayBlockRegistry = createBlockRegistry([
	...BLOCK_DEFS,
	...V2_BLOCK_DEFS,
])

/** v1 items, the v2 items of gameplay, and the v2 block items. */
export const ITEMS_V2: GameplayItemRegistry = createItemRegistry([
	...ITEM_DEFS,
	...ITEM_V2_DEFS,
	...V2_BLOCK_ITEM_DEFS,
])

/** Stack limit resolver that also knows the v2 items. */
export function v2StackLimitOf(item: ItemId): number {
	return ITEMS_V2.maxStackOf(item)
}

/**
 * Inventory options for every call this app makes: without them the shared
 * `registryStackLimit` would resolve a v2 item against the v1 registry.
 */
export const V2_INVENTORY = { stackLimitOf: v2StackLimitOf }

/** Display name of an item, including the v2 items. */
export function itemDisplayName(item: ItemId): string {
	return ITEMS_V2.tryById(item)?.displayName ?? `Item ${item}`
}

/** Display name of a block, including the v2 blocks. */
export function blockDisplayName(id: BlockId): string {
	return BLOCKS_V2.tryById(id)?.displayName ?? `Block ${id}`
}

/** Durability of an item, including the v2 tools. 0 when not damageable. */
export function v2MaxDurabilityOf(item: ItemId): number {
	return ITEMS_V2.tryById(item)?.durability ?? 0
}

/** Block an item places, or `null` for items that are not blocks. */
export function v2PlacesBlock(item: ItemId): BlockId | null {
	return ITEMS_V2.tryById(item)?.placesBlock ?? null
}
