export {
	canMerge,
	cloneItemStack,
	damageStack,
	isDamageable,
	isStackEmpty,
	makeStack,
	maxDurabilityOf,
	normalizeStack,
	registryStackLimit,
	remainingDurability,
	splitStack,
	stackLimitOf,
	type StackLimitResolver,
} from './stacks'
export {
	BARE_HAND,
	breakTimeWith,
	canHarvestWith,
	isPreferredTool,
	toolProfileOf,
	type ToolProfile,
} from './tools'
export {
	addStack,
	clearCraftingGrid,
	clearInventory,
	cloneInventoryState,
	consumeHeld,
	countItem,
	craftingGridSize,
	createInventoryState,
	cycleHotbar,
	damageHeld,
	damageSlot,
	findItem,
	getCraftingSlot,
	getSlot,
	hasRoomFor,
	heldStack,
	inventoryContents,
	isCreative,
	isInventoryEmpty,
	removeItem,
	resizeCraftingGrid,
	selectHotbar,
	setCraftingSlot,
	setHeldStack,
	setSlot,
	swapCursorWithSlot,
	takeFromSlot,
	type InventoryOptions,
} from './inventory'
